### ISSUE TITLE
Documentation clarification 

### ISSUE THREAD

**Issue by TheRockStarDBA** [qlik-oss/gopherciser#436]
I am using the latest version of gopherciser. Have 3 questions :

1. What are the `Sent (bytes) and Received (Bytes)` denote ? 
2. How can I get how much memory my app or sheet uses ? 
3. Is there a way to log cpu, memory, etc to a log file ? 

Thanks !

**Comment by DnlLrssn** [comment]
>     1. What are the `Sent (bytes) and Received (Bytes)` denote ?
> 

This is the total sent and received by the tool simulating users, the uncompressed value is reported. 

>     2. How can I get how much memory my app or sheet uses ?
> 

No the tool does not have access to server performance counters etc. Using "Evaluate performance" in Qlik Cloud could get you some memory values for the entire app in the downloadable log (if you have access to Qlik Cloud). 

>     3. Is there a way to log cpu, memory, etc to a log file ?
> 

Not in the log no, as tool does not have access to admin the target server ( by design). I would recommend setting up performance counters on the server, instructions how to do this can be found in the PDF accompanying the [Qlik Sense Enterprise Tools](https://community.qlik.com/t5/Scalability/Qlik-Sense-Enterprise-Scalability-Tools/td-p/1579916) on Qlik community. The tool log and the performance counters can then be analyzed in a Qlik Sense app such as [QSSTAnalyzer](https://community.qlik.com/t5/Scalability/Scalability-Results-Analyzer/td-p/1493648)
